//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachelor_app.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bachelor_app.Language.Resources.Resources_en-EN", typeof(Resources_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        public static string BasicStack {
            get {
                return ResourceManager.GetString("BasicStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block matching with CUDA.
        /// </summary>
        public static string CudaStereoBM {
            get {
                return ResourceManager.GetString("CudaStereoBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belief propagation with CUDA.
        /// </summary>
        public static string CudaStereoConstantSpaceBP {
            get {
                return ResourceManager.GetString("CudaStereoConstantSpaceBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth map.
        /// </summary>
        public static string DepthMap {
            get {
                return ResourceManager.GetString("DepthMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor matches.
        /// </summary>
        public static string DescriptorsMatches {
            get {
                return ResourceManager.GetString("DescriptorsMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computed keypoints.
        /// </summary>
        public static string DrawnKeyPoint {
            get {
                return ResourceManager.GetString("DrawnKeyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computed descriptor matches.
        /// </summary>
        public static string DrawnMatches {
            get {
                return ResourceManager.GetString("DrawnMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key points.
        /// </summary>
        public static string KeyPoints {
            get {
                return ResourceManager.GetString("KeyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left camera.
        /// </summary>
        public static string LeftCamera {
            get {
                return ResourceManager.GetString("LeftCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack for left camera.
        /// </summary>
        public static string LeftCameraStack {
            get {
                return ResourceManager.GetString("LeftCameraStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point cloud.
        /// </summary>
        public static string PointCloud {
            get {
                return ResourceManager.GetString("PointCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right camera.
        /// </summary>
        public static string RightCamera {
            get {
                return ResourceManager.GetString("RightCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack for right camera.
        /// </summary>
        public static string RightCameraStack {
            get {
                return ResourceManager.GetString("RightCameraStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        public static string Stack {
            get {
                return ResourceManager.GetString("Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block matching.
        /// </summary>
        public static string StereoBM {
            get {
                return ResourceManager.GetString("StereoBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-global block matching.
        /// </summary>
        public static string StereoSGBM {
            get {
                return ResourceManager.GetString("StereoSGBM", resourceCulture);
            }
        }
    }
}
