//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachelor_app.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_sk_SK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_sk_SK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bachelor_app.Language.Resources.Resources_sk-SK", typeof(Resources_sk_SK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth map  SK.
        /// </summary>
        public static string DepthMap {
            get {
                return ResourceManager.GetString("DepthMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key points  SK.
        /// </summary>
        public static string KeyPoints {
            get {
                return ResourceManager.GetString("KeyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key points matches  SK.
        /// </summary>
        public static string KeyPointsMatches {
            get {
                return ResourceManager.GetString("KeyPointsMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left camera SK.
        /// </summary>
        public static string LeftCamera {
            get {
                return ResourceManager.GetString("LeftCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List viewer  SK.
        /// </summary>
        public static string ListViewer {
            get {
                return ResourceManager.GetString("ListViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point cloud  SK.
        /// </summary>
        public static string PointCloud {
            get {
                return ResourceManager.GetString("PointCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right camera  SK.
        /// </summary>
        public static string RightCamera {
            get {
                return ResourceManager.GetString("RightCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo Block Matching  SK.
        /// </summary>
        public static string StereoBlockMatching {
            get {
                return ResourceManager.GetString("StereoBlockMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StereoBM SK.
        /// </summary>
        public static string StereoBM {
            get {
                return ResourceManager.GetString("StereoBM", resourceCulture);
            }
        }
    }
}
